# -*- coding: utf-8 -*-
"""rto-weather-agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbcVktMtUZSuLRzF5h8o8g-7jb02l_oE
"""

import os
import requests
import pandas as pd
import itertools
import smtplib
import ssl
from datetime import datetime, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from google import genai

# --- Configuration (Environment Variables for Cloud Run) ---
LAT, LON = 45.5017, -73.5673  # Montreal
COMMUTE_HOURS = [8, 16]       # 8:00 AM and 4:00 PM only
OFFICE_WINDOW = range(8, 19)  # 8 AM to 6 PM

# Secrets - These should be set in your Cloud Run "Variables & Secrets" tab
RECIPIENT_EMAIL = os.environ.get("RECEIVER_EMAIL")
SENDER_EMAIL = os.environ.get("SENDER_EMAIL")
SENDER_PASSWORD = os.environ.get("SENDER_APP_PASSWORD")
GEMINI_API_KEY = os.environ.get("GOOGLE_API_KEY")
#GEMINI_MODEL = "gemini-2.5-flash-lite"
GEMINI_MODEL = "gemma-4-31b-it"


def get_weather_data():
    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        "latitude": LAT, "longitude": LON,
        "hourly": ["temperature_2m", "precipitation_probability", "weather_code", "precipitation"],
        "timezone": "America/New_York", "forecast_days": 10
    }
    r = requests.get(url, params=params)
    r.raise_for_status()
    return r.json()

def get_weather_desc(code):
    if code in [56, 57, 66, 67]: return "Freezing Rain"
    if 51 <= code <= 65 or 80 <= code <= 82: return "Rain"
    if 71 <= code <= 77 or 85 <= code <= 86: return "Snow"
    return "Clear"

def calculate_quality_penalty(row):
    h = row['time'].hour
    if h not in OFFICE_WINDOW: return 0

    if row['prob'] < 30 and row['precip_mm'] < 0.7 and row['temp'] >= -10:
        return 0

    penalty = 0
    is_commute = h in COMMUTE_HOURS
    desc = get_weather_desc(row['code'])

    if desc == "Freezing Rain": penalty = -100
    elif desc == "Rain": penalty = -70
    elif desc == "Snow": penalty = -40
    elif row['temp'] < -10: penalty = -30

    prob_mult = 2.5 if row['prob'] >= 90 else 2.0 if row['prob'] >= 70 else 1.5 if row['prob'] >= 50 else 1.0
    timing_mult = 4.0 if is_commute else 1.0

    return round(penalty * prob_mult * timing_mult, 1)

def send_email(html_content, subject):
    msg = MIMEMultipart()
    msg['Subject'] = subject
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECIPIENT_EMAIL
    msg.attach(MIMEText(html_content, 'html'))

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())

def main_handler(request):

    # --- DIAGNOSTIC: CHECK THE KEY ---
    api_key = os.environ.get("GOOGLE_API_KEY")

    if not api_key:
        print("ERROR: GOOGLE_API_KEY environment variable is MISSING in Cloud Run settings.")
        return "Config Error: Key Missing", 500

    # Optional: Print the first 4 characters of the key to the logs to verify it's the NEW one
    print(f"DEBUG: Using API Key starting with: {api_key[:4]}...")
    # ---------------------------------

    # 1. Fetch & Process
    raw = get_weather_data()
    df_h = pd.DataFrame({
        "time": pd.to_datetime(raw["hourly"]["time"]),
        "temp": raw["hourly"]["temperature_2m"],
        "prob": raw["hourly"]["precipitation_probability"],
        "code": raw["hourly"]["weather_code"],
        "precip_mm": raw["hourly"]["precipitation"]
    })
    df_h['quality_score'] = df_h.apply(calculate_quality_penalty, axis=1)

    # 2. Date Logic
    today = datetime.now().date()
    days_to_mon = (0 - today.weekday()) % 7
    if days_to_mon == 0: days_to_mon = 7
    next_mon = today + timedelta(days=days_to_mon)
    target_dates = [next_mon + timedelta(days=i) for i in range(5)]

    # 3. Analyze Days
    w1_summary = []
    for d in target_dates:
        day_h = df_h[(df_h['time'].dt.date == d) & (df_h['time'].dt.hour.isin(OFFICE_WINDOW))]
        day_score = day_h['quality_score'].sum()

        # Commute Audit (8 AM and 4 PM)
        day_alerts = []
        for _, row in day_h[day_h['time'].dt.hour.isin(COMMUTE_HOURS)].iterrows():
            if row['quality_score'] < 0:
                cond = get_weather_desc(row['code'])
                label = "To Office" if row['time'].hour == 8 else "From Office"
                day_alerts.append(f"{label}: {cond} ({row['prob']}%)")

        w1_summary.append({
            "day": d.strftime('%A'),
            "date": d.strftime('%Y-%m-%d'),
            "quality": round(day_score, 1),
            "temp": round(day_h['temp'].mean(), 1),
            "prob": int(pd.Series(day_h['prob'].max()).fillna(0).iloc[0]),
            "mm": round(day_h['precip_mm'].sum(), 1),
            "alerts": day_alerts
        })

    # 4. Solve RTO Combination
    best_combo, max_q = None, -float('inf')
    for combo in itertools.combinations(w1_summary, 3):
        names = [c['day'] for c in combo]
        if 'Monday' in names or 'Friday' in names:
            curr_score = sum([c['quality'] for c in combo])
            if curr_score > max_q:
                max_q, best_combo = curr_score, combo

    # 5. AI Reasoning
    client = genai.Client(api_key=GEMINI_API_KEY)
    ai_prompt = (
        f"You are Daniel's professional RTO assistant. Address him as Daniel.\n"
        f"Hi Daniel, I have already selected these 3 days for you: {[d['day'] for d in best_combo]}.\n"
        f"Daniel's policy: 3 days/week, must include Monday or Friday.\n"
        f"Preferences: Sunny > Cold > Snow > Rain. Daniel hates rain.\n\n"
        f"WEEK DATA: {w1_summary}\n\n"
        f"TASK: Explain why I picked these days. Use the 'alerts' and 'mm' of rain to be specific.\n"
        f"IMPORTANT: Do NOT use Markdown (no ** or #). Use only HTML tags like <b> and <br> for formatting."
        f"Be helpful, friendly, and concise."
    )
    response = client.models.generate_content(model=GEMINI_MODEL, contents=ai_prompt)

    # Clean any accidental markdown code blocks if the AI provides them
    explanation_html = response.text.replace('```html', '').replace('```', '').strip()

    # 6. Build HTML Email
    table_rows = ""
    for d in w1_summary:
        is_selected = d['day'] in [x['day'] for x in best_combo]
        bg = "#e8f5e9" if is_selected else "#ffffff"
        font_weight = "bold" if is_selected else "normal"
        alerts = " | ".join(d['alerts']) if d['alerts'] else "Dry"

        table_rows += f"""
        <tr style="background-color: {bg}; border-bottom: 1px solid #ddd; font-weight: {font_weight};">
            <td style="padding: 10px;">{d['day']}</td>
            <td style="padding: 10px;">{d['temp']}°C</td>
            <td style="padding: 10px;">{d['prob']}%</td>
            <td style="padding: 10px;">{d['mm']}mm</td>
            <td style="padding: 10px;">{alerts}</td>
        </tr>
        """

    email_html = f"""
    <html><body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color: #2c3e50;">🚀 Daniel's RTO Advisory: {w1_summary[0]['date']}</h2>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
            <tr style="background: #f8f9fa; text-align: left; border-bottom: 2px solid #dee2e6;">
                <th style="padding: 10px;">Day</th><th style="padding: 10px;">Temp</th>
                <th style="padding: 10px;">Max Prob</th><th style="padding: 10px;">Rain mm</th>
                <th style="padding: 10px;">Commute Alert</th>
            </tr>
            {table_rows}
        </table>
        <div style="padding: 15px; background: #f1f3f5; border-radius: 8px; border: 1px solid #ddd;">
            <h3 style="margin-top: 0; color: #00796b;">Assistant Analysis</h3>
            {explanation_html}
        </div>
    </body></html>
    """

    subject = f"Daniel's RTO Strategy: {w1_summary[0]['date']}"
    send_email(email_html, subject)
    return "OK", 200

if __name__ == "__main__":
    main_handler()

